version: '3.3'

services:
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        env_file: ./.env
        volumes:
            - 'mdb:/var/lib/mysql'
        restart: always
        networks:
            - inception_net
    
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - 'wp:/var/www/html'
        ports:
            - '9000:9000'
        restart: always
        environment: 
            - WORDPRESS_DB_HOST=mariadb:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=$MYSQL_DATABASE
        networks:
            - inception_net
        depends_on:
            - mariadb
        
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        volumes:
            - 'wp:/var/www/html'
            - '/Users/danila/Desktop/inception/srcs/requirements/nginx/srcs/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '443:443'
        restart: always
        networks:
            - inception_net
        depends_on:
            - wordpress

volumes:
    wp:
    mdb:

networks:
    inception_net:
        driver: bridge